<Project>
  <Import Project="$(MSBuildThisFileDirectory)../Directory.Build.props" />
  <Import
    Project="$(MSBuildProjectDirectory)/Taiwu.Mod.props"
    Condition="Exists('$(MSBuildProjectDirectory)/Taiwu.Mod.props')"
  />

  <PropertyGroup>
    <TargetFramework
      Condition="'$(TargetFramework)' == '' And '$(TaiwuModSide)' == 'Frontend'"
    >netstandard2.1</TargetFramework>
    <TargetFramework
      Condition="'$(TargetFramework)' == '' And '$(TaiwuModSide)' == 'Backend'"
    >net6.0</TargetFramework>
    <TargetFramework Condition="'$(TargetFramework)' == ''"
    >netstandard2.1</TargetFramework>
    <AssemblyName Condition="'$(AssemblyName)' == ''"
    >$(MSBuildProjectName)</AssemblyName>
    <RootNamespace Condition="'$(RootNamespace)' == ''"
    >$(MSBuildProjectName)</RootNamespace>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <InternalizeRuntimeDependencies
      Condition="'$(InternalizeRuntimeDependencies)' == ''"
    >true</InternalizeRuntimeDependencies>
    <RenameInternalizedDependencies
      Condition="'$(RenameInternalizedDependencies)' == ''"
    >true</RenameInternalizedDependencies>
    <AllowDuplicateInternalizedResources
      Condition="'$(AllowDuplicateInternalizedResources)' == ''"
    >false</AllowDuplicateInternalizedResources>
    <ILRepackTargetsFile Condition="'$(ILRepackTargetsFile)' == ''"
    >$(MSBuildThisFileDirectory)Taiwu.Mod.ILRepack.targets</ILRepackTargetsFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(TaiwuModSide)' != ''">
    <PackageReference
      Include="ILRepack.Lib.MSBuild.Task"
      PrivateAssets="all"
      Condition="'$(InternalizeRuntimeDependencies)' != 'false'"
    />
    <PackageReference
      Include="Krafs.Publicizer"
      PrivateAssets="all"
      Condition="'$(UsePublicizer)' == 'true'"
    />
    <PackageReference
      Include="Taiwu.ModKit.References.Plugin"
      PrivateAssets="all"
    />
  </ItemGroup>
</Project>
